version: '3.3'

services:
  # Database
  db:
    image: mariadb:10.4.17
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: herfstzorg
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - wpsite
  # WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: herfstzorg
    volumes:
      - .:/var/www/html/wp-content/themes/wp-herfstzorg-1.05
    networks:
      - wpsite
  # PHPMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: {}